/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletsRouteImport } from './routes/wallets'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as IntelRouteImport } from './routes/intel'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AppRouteImport } from './routes/app'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WalletsAddressRouteImport } from './routes/wallets.$address'
import { Route as ApiEventsRouteImport } from './routes/api/events'
import { Route as ApiWebhooksHeliusRouteImport } from './routes/api/webhooks/helius'

const WalletsRoute = WalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelRoute = IntelRouteImport.update({
  id: '/intel',
  path: '/intel',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletsAddressRoute = WalletsAddressRouteImport.update({
  id: '/$address',
  path: '/$address',
  getParentRoute: () => WalletsRoute,
} as any)
const ApiEventsRoute = ApiEventsRouteImport.update({
  id: '/api/events',
  path: '/api/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksHeliusRoute = ApiWebhooksHeliusRouteImport.update({
  id: '/api/webhooks/helius',
  path: '/api/webhooks/helius',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/app': typeof AppRoute
  '/audit': typeof AuditRoute
  '/intel': typeof IntelRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/settings': typeof SettingsRoute
  '/wallets': typeof WalletsRouteWithChildren
  '/api/events': typeof ApiEventsRoute
  '/wallets/$address': typeof WalletsAddressRoute
  '/api/webhooks/helius': typeof ApiWebhooksHeliusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/app': typeof AppRoute
  '/audit': typeof AuditRoute
  '/intel': typeof IntelRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/settings': typeof SettingsRoute
  '/wallets': typeof WalletsRouteWithChildren
  '/api/events': typeof ApiEventsRoute
  '/wallets/$address': typeof WalletsAddressRoute
  '/api/webhooks/helius': typeof ApiWebhooksHeliusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/app': typeof AppRoute
  '/audit': typeof AuditRoute
  '/intel': typeof IntelRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/settings': typeof SettingsRoute
  '/wallets': typeof WalletsRouteWithChildren
  '/api/events': typeof ApiEventsRoute
  '/wallets/$address': typeof WalletsAddressRoute
  '/api/webhooks/helius': typeof ApiWebhooksHeliusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/app'
    | '/audit'
    | '/intel'
    | '/onboarding'
    | '/pricing'
    | '/settings'
    | '/wallets'
    | '/api/events'
    | '/wallets/$address'
    | '/api/webhooks/helius'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/app'
    | '/audit'
    | '/intel'
    | '/onboarding'
    | '/pricing'
    | '/settings'
    | '/wallets'
    | '/api/events'
    | '/wallets/$address'
    | '/api/webhooks/helius'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/app'
    | '/audit'
    | '/intel'
    | '/onboarding'
    | '/pricing'
    | '/settings'
    | '/wallets'
    | '/api/events'
    | '/wallets/$address'
    | '/api/webhooks/helius'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  AppRoute: typeof AppRoute
  AuditRoute: typeof AuditRoute
  IntelRoute: typeof IntelRoute
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
  SettingsRoute: typeof SettingsRoute
  WalletsRoute: typeof WalletsRouteWithChildren
  ApiEventsRoute: typeof ApiEventsRoute
  ApiWebhooksHeliusRoute: typeof ApiWebhooksHeliusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallets': {
      id: '/wallets'
      path: '/wallets'
      fullPath: '/wallets'
      preLoaderRoute: typeof WalletsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intel': {
      id: '/intel'
      path: '/intel'
      fullPath: '/intel'
      preLoaderRoute: typeof IntelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallets/$address': {
      id: '/wallets/$address'
      path: '/$address'
      fullPath: '/wallets/$address'
      preLoaderRoute: typeof WalletsAddressRouteImport
      parentRoute: typeof WalletsRoute
    }
    '/api/events': {
      id: '/api/events'
      path: '/api/events'
      fullPath: '/api/events'
      preLoaderRoute: typeof ApiEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/helius': {
      id: '/api/webhooks/helius'
      path: '/api/webhooks/helius'
      fullPath: '/api/webhooks/helius'
      preLoaderRoute: typeof ApiWebhooksHeliusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface WalletsRouteChildren {
  WalletsAddressRoute: typeof WalletsAddressRoute
}

const WalletsRouteChildren: WalletsRouteChildren = {
  WalletsAddressRoute: WalletsAddressRoute,
}

const WalletsRouteWithChildren =
  WalletsRoute._addFileChildren(WalletsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  AppRoute: AppRoute,
  AuditRoute: AuditRoute,
  IntelRoute: IntelRoute,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
  SettingsRoute: SettingsRoute,
  WalletsRoute: WalletsRouteWithChildren,
  ApiEventsRoute: ApiEventsRoute,
  ApiWebhooksHeliusRoute: ApiWebhooksHeliusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
