/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiEventsRouteImport } from './routes/api/events'
import { Route as ApiWebhooksHeliusRouteImport } from './routes/api/webhooks/helius'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsRoute = ApiEventsRouteImport.update({
  id: '/api/events',
  path: '/api/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksHeliusRoute = ApiWebhooksHeliusRouteImport.update({
  id: '/api/webhooks/helius',
  path: '/api/webhooks/helius',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/api/events': typeof ApiEventsRoute
  '/api/webhooks/helius': typeof ApiWebhooksHeliusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/api/events': typeof ApiEventsRoute
  '/api/webhooks/helius': typeof ApiWebhooksHeliusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/api/events': typeof ApiEventsRoute
  '/api/webhooks/helius': typeof ApiWebhooksHeliusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/settings' | '/api/events' | '/api/webhooks/helius'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/settings' | '/api/events' | '/api/webhooks/helius'
  id: '__root__' | '/' | '/settings' | '/api/events' | '/api/webhooks/helius'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  ApiEventsRoute: typeof ApiEventsRoute
  ApiWebhooksHeliusRoute: typeof ApiWebhooksHeliusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events': {
      id: '/api/events'
      path: '/api/events'
      fullPath: '/api/events'
      preLoaderRoute: typeof ApiEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/helius': {
      id: '/api/webhooks/helius'
      path: '/api/webhooks/helius'
      fullPath: '/api/webhooks/helius'
      preLoaderRoute: typeof ApiWebhooksHeliusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  ApiEventsRoute: ApiEventsRoute,
  ApiWebhooksHeliusRoute: ApiWebhooksHeliusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
